version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker login
          command: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

      - run:
          name: make
          command: make all

      - run:
          name: docker push
          command: docker push rfaircloth/splunkcontainer:latest